/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
import tarea9.DBDepartamentos;
import tarea9.Departamentos;

/**
 *
 * @author Ivan
 */
public class Ventana extends javax.swing.JFrame {

    DBDepartamentos db;

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        db = new DBDepartamentos();
        db.conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelIzquierdo = new javax.swing.JPanel();
        labelCodigo = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        LabelLocalizacion = new javax.swing.JLabel();
        labelManager = new javax.swing.JLabel();
        textoCodigo = new javax.swing.JTextField();
        textoNombre = new javax.swing.JTextField();
        textoLocalizacion = new javax.swing.JTextField();
        textoManager = new javax.swing.JTextField();
        javax.swing.JButton buttonInsertar = new javax.swing.JButton();
        buttonModificar = new javax.swing.JToggleButton();
        buttonBorrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanelDerecho = new javax.swing.JPanel();
        labelLista = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDepartamentos = new javax.swing.JTextArea();
        buttonMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelIzquierdo.setPreferredSize(new java.awt.Dimension(313, 330));

        labelCodigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelCodigo.setText("Codigo");

        labelNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelNombre.setText("Nombre");

        LabelLocalizacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelLocalizacion.setText("Id Localización");
        LabelLocalizacion.setToolTipText("");

        labelManager.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelManager.setText("Id Manager");

        buttonInsertar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonInsertar.setText("Insertar");
        buttonInsertar.setPreferredSize(new java.awt.Dimension(75, 25));
        buttonInsertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonInsertarMouseClicked(evt);
            }
        });

        buttonModificar.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        buttonModificar.setText("Modificar");
        buttonModificar.setPreferredSize(new java.awt.Dimension(75, 25));
        buttonModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonModificarMouseClicked(evt);
            }
        });

        buttonBorrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonBorrar.setText("Borrar");
        buttonBorrar.setPreferredSize(new java.awt.Dimension(75, 25));
        buttonBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonBorrarMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Datos de departamento");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanelIzquierdoLayout = new javax.swing.GroupLayout(jPanelIzquierdo);
        jPanelIzquierdo.setLayout(jPanelIzquierdoLayout);
        jPanelIzquierdoLayout.setHorizontalGroup(
            jPanelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIzquierdoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIzquierdoLayout.createSequentialGroup()
                        .addComponent(buttonInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelIzquierdoLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelLocalizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoLocalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoManager, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIzquierdoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        jPanelIzquierdoLayout.setVerticalGroup(
            jPanelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIzquierdoLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelLocalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoLocalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelManager, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoManager, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jPanelDerecho.setPreferredSize(new java.awt.Dimension(313, 330));

        labelLista.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelLista.setText("Mostrar datos del departamento");

        txtAreaDepartamentos.setColumns(20);
        txtAreaDepartamentos.setRows(5);
        txtAreaDepartamentos.setTabSize(6);
        jScrollPane1.setViewportView(txtAreaDepartamentos);

        buttonMostrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonMostrar.setText("Mostrar");
        buttonMostrar.setPreferredSize(new java.awt.Dimension(75, 25));
        buttonMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMostrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelDerechoLayout = new javax.swing.GroupLayout(jPanelDerecho);
        jPanelDerecho.setLayout(jPanelDerechoLayout);
        jPanelDerechoLayout.setHorizontalGroup(
            jPanelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDerechoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanelDerechoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(labelLista)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelDerechoLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(buttonMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDerechoLayout.setVerticalGroup(
            jPanelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDerechoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelLista)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(buttonMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelDerecho, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelIzquierdo, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addComponent(jPanelDerecho, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiar() {
        // Limpia el campo de texto del nombre
        this.textoNombre.setText("");
        // Limpia el campo de texto de la cantidad
        this.textoLocalizacion.setText("");
        // Limpia el campo de texto del código
        this.textoCodigo.setText("");
        // Limpia el campo de texto de la descripción
        this.textoManager.setText("");
    }

// Método que se ejecuta cuando el usuario hace clic en el botón "Insertar"
    private void buttonInsertarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonInsertarMouseClicked
        //Obtiene el texto de los campos de texto y crea un objeto Departamentos
        Departamentos dept = new Departamentos(Integer.parseInt(textoCodigo.getText()),
                textoNombre.getText(),
                Integer.parseInt(textoManager.getText()),
                Integer.parseInt(textoLocalizacion.getText()));
        // Llama al método insertar de la variable db
        boolean insertado = db.insertar(dept);
        // Establece el mensaje en el área de texto del GUI para informar 
        //al usuario del resultado de la inserción
        if (insertado) {
            txtAreaDepartamentos.setText("Departamento insertado con éxito.\n"
                    + db.mostrar());
        } else {
            txtAreaDepartamentos.setText("Error al insertar el departamento. "
                    + "El código ya existe o hubo un error en la base de datos."
                    + "\n" + db.mostrar());
        }
        // Llama al método limpiar().
        limpiar();
    }//GEN-LAST:event_buttonInsertarMouseClicked

    // Método que se ejecuta cuando el usuario hace clic en el botón "Modificar"
    private void buttonModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonModificarMouseClicked

        // Obtiene el código del departamento del campo de texto y lo convierte 
        //a entero
        int codigo = Integer.parseInt(this.textoCodigo.getText());
        // Obtiene el nombre del departamento del campo de texto
        String nombre = textoNombre.getText();

        // Si el campo nombre está vacío, busca el departamento en la base de 
        //datos
        if (nombre.isEmpty()) {
            Departamentos dept = db.buscar(codigo);
            if (dept != null) {
                // Si el departamento es encontrado, llena los campos de texto 
                //con los datos del departamento
                textoNombre.setText(dept.getNombre());
                textoLocalizacion.setText("" + dept.getId_localizacion());
                textoManager.setText("" + dept.getId_manager());
                return;
            } else {
                // Si no se encuentra el departamento, muestra un mensaje de 
                //error
                txtAreaDepartamentos.setText("No se ha encontrado el departamento");
                return;
            }
        }
        //Crea un objeto Departamentos con los nuevos datos obtenidos de los 
        //campos de texto
        Departamentos dept = new Departamentos(codigo, textoNombre.getText(),
                Integer.parseInt(textoLocalizacion.getText()),
                Integer.parseInt(textoManager.getText()));

        // Llama al método modificar de la variable db
        boolean modificado = db.modificar(dept);
        // Llama al método mostrar y actualiza el área de texto con los datos 
        //actuales de los departamentos
        if (modificado) {
            txtAreaDepartamentos.setText("Departamento modificado con éxito.\n" 
                    + db.mostrar());
            
        } else {
            txtAreaDepartamentos.setText("Error al modificar el departamento.\n" 
                    + db.mostrar());
        }
    }//GEN-LAST:event_buttonModificarMouseClicked
    // Método que se ejecuta cuando el usuario hace clic en el botón "Borrar"
    private void buttonBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBorrarMouseClicked
        //Obtiene el código ingresado en el campo de texto 'textoCodigo'
        int codigo = Integer.parseInt(this.textoCodigo.getText());
        
        // Obtiene el nombre del departamento del campo de texto
        String nombre = textoNombre.getText();
        // Si el campo nombre está vacío, busca el departamento en la base de 
        //datos
        if (nombre.isEmpty()) {
            Departamentos dept = db.buscar(codigo);
            if (dept != null) {
                // Si el departamento es encontrado, llena los campos de texto 
                //con los datos del departamento
                textoNombre.setText(dept.getNombre());
                textoLocalizacion.setText("" + dept.getId_localizacion());
                textoManager.setText("" + dept.getId_manager());
                return;
                // Si no se encuentra el departamento, muestra un mensaje de 
                //error
            } else {
                txtAreaDepartamentos.setText("No se ha encontrado el departamento");
                return;
            }
        }

        Departamentos dept = new Departamentos(codigo, textoNombre.getText(),
                Integer.parseInt(textoLocalizacion.getText()),
                Integer.parseInt(textoManager.getText()));
        int respuesta = JOptionPane.showConfirmDialog(null,
                "¿Quieres borrar el departamento?",
                "Confirmar borrado",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        //Llama al metodo borrar
        if (respuesta == JOptionPane.YES_NO_OPTION) {
            // Borra el departamento si la respuesta del usuario es afirmativa
            db.borrar(dept);
            JOptionPane.showMessageDialog(null, "Departamento borrado "
                    + "correctamente.", "Borrado",
                    JOptionPane.INFORMATION_MESSAGE);
            this.txtAreaDepartamentos.setText(db.mostrar());
            limpiar();
        } else {
            JOptionPane.showMessageDialog(null, "Borrado cancelado.",
                    "Cancelado", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buttonBorrarMouseClicked

    private void buttonMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMostrarMouseClicked
        //Llama al metodo mostar().
        String mensaje = db.mostrar();
        // Establece el mensaje en el área de texto del GUI
        this.txtAreaDepartamentos.setText(mensaje);

    }//GEN-LAST:event_buttonMostrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelLocalizacion;
    private javax.swing.JButton buttonBorrar;
    private javax.swing.JToggleButton buttonModificar;
    private javax.swing.JButton buttonMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelDerecho;
    private javax.swing.JPanel jPanelIzquierdo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelLista;
    private javax.swing.JLabel labelManager;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JTextField textoCodigo;
    private javax.swing.JTextField textoLocalizacion;
    private javax.swing.JTextField textoManager;
    private javax.swing.JTextField textoNombre;
    private javax.swing.JTextArea txtAreaDepartamentos;
    // End of variables declaration//GEN-END:variables
}
